project:
  type: website

website:
  title: "Fabrizio Mafessoni"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching/index.qmd
        text: Teaching
    right:
      - icon: github
        href: https://github.com/fabrimafe
format:
  html:
    theme: minty
    toc: true
